version: '3'
services:
  backend: 
    image: nginx:latest
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./backend-ssl/:/etc/nginx/ssl/
      - ./TLS-config/TLS1.3-params.conf:/etc/nginx/conf.d/ssl-params.conf
      - ./nginx-config/nginx-backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    ports:
      - 8080:443

  # proxy:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx-config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - backend
  #     - proxy
  
  # frontend: 
  #   image: nginx:latest
  #   volumes:
  #     - ./frontend-ssl/:/etc/nginx/ssl/
  #     - ./TLS-config/TLS1.3-params.conf:/etc/nginx/conf.d/ssl-params.conf
  #     - ./nginx-config/nginx-frontend.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 443:443
  #   networks:
  #     - frontend
  #     - proxy

networks:
  backend:
  proxy:
  frontend: