version: '3'
services:
  backend: 
    image: nginx:latest
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./backend-ssl/:/etc/nginx/ssl/
      - ./TLS-config/TLS1.2-params.conf:/etc/nginx/conf.d/ssl-params.conf
      - ./nginx-config/nginx-backend-http2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    ports:
      - 443:443

networks:
  backend: